### ISSUE TITLE
Bug in checksum checks

### ISSUE THREAD

**Issue by nagylzs** [bitnami/bitnami-docker-postgresql-repmgr#103] opened 2022-01-04 08:03 UTC
There is a bug in checksum checking. It may also affect other bitnami images.

Here is an example line from the `Dockerfile`:

```
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "postgresql-repmgr" "14.1.0-1" --checksum 3bde221401b04731b264e8966742d43e8516064c46a9a4559d9a2d2bf404fde5
```

If you clone this project, and change the above checksum, then the "docker build" command still succeeds. It is true,that it complains about the checksum error:

```
Downloading postgresql-repmgr-14.1.0-1-linux-amd64-debian-10 package
Verifying package integrity
postgresql-repmgr-14.1.0-1-linux-amd64-debian-10.tar.gz: FAILED
sha256sum: WARNING: 1 computed checksum did NOT match
```

But the docker build command succeeds anyway:

```
Step 20/20 : CMD [ "/opt/bitnami/scripts/postgresql-repmgr/run.sh" ]
 ---> Running in 46daf3c30b79
Removing intermediate container 46daf3c30b79
 ---> 7609f4aaf76d
Successfully built 7609f4aaf76d
Successfully tagged test:latest
```

I think that the build command should return with error message.

**Comment by carrodher** [comment] 2022-01-04 14:31
Thanks for letting us know, this was a regression recently introduced. We are testing some changes to make the `docker build` command fail if the checksum is not valid or doesn't match.

With the tests we are doing this should be the result:
```diff
-RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "ini-file" "1.4.1-0" --checksum 3d189e4b1fcdc330fb84c14a7c6fb296def127d3142d9a17fe0c9a5dba51ef6d
+RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "ini-file" "1.4.1-0" --checksum 3d189e4b1fcdc330fb84c14a7c6fb296def127d3142d9a17fe0c90000000000
```
```console
$ docker build . -t carrodher/mysql
...
Step 6/17 : RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "ini-file" "1.4.1-0" --checksum 3d189e4b1fcdc330fb84c14a7c6fb296def127d3142d9a17fe0c90000000000
 ---> Running in 5b18349a4df6
 Downloading ini-file-1.4.1-0-linux-amd64-debian-10 package
 Verifying package integrity
 ini-file-1.4.1-0-linux-amd64-debian-10.tar.gz: FAILED
 sha256sum: WARNING: 1 computed checksum did NOT match
 The command '/bin/sh -c . /opt/bitnami/scripts/libcomponent.sh && component_unpack "ini-file" "1.4.1-0" --checksum 3d189e4b1fcdc330fb84c14a7c6fb296def127d3142d9a17fe0c90000000000' returned a non-zero code: 1
```

I will update this issue once released a new container image including the changes

**Comment by carrodher** [comment] 2022-01-04 15:42
New container images are being released, see https://github.com/bitnami/bitnami-docker-postgresql-repmgr/commit/ea69dff7c134291e91aaec6653e2a089035bfc21 as an example, the rest of the branches will be released during the next hours.

Using the recently released code:
- Valid checksum:
```console
$ docker build . -t carrodher/test
Sending build context to Docker daemon  207.4kB
...
Step 6/20 : RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "postgresql-repmgr" "10.19.0-1" --checksum d4f2261f855e87f4f7fa8f9eaa923798d8824938a5fd8f9eb1ac4782a82f9f09
 ---> Running in 38682d57fbd1
Downloading postgresql-repmgr-10.19.0-1-linux-amd64-debian-10 package
Verifying package integrity
postgresql-repmgr-10.19.0-1-linux-amd64-debian-10.tar.gz: OK
Removing intermediate container 38682d57fbd1
 ---> 778fd30052dc
...
Successfully built 6710af3ff3bb
Successfully tagged carrodher/test:latest

$ echo $?
0
```
- Wrong checksum:
```diff
COPY prebuildfs /
# Install required system packages and dependencies
RUN install_packages acl ca-certificates curl gzip libbsd0 libc6 libedit2 libffi6 libgcc1 libgmp10 libgnutls30 libhogweed4 libicu63 libidn2-0 libldap-2.4-2 liblzma5 libnettle6 libp11-kit0 libpcre3 libreadline7 libsasl2-2 libsqlite3-0 libssl1.1 libstdc++6 libtasn1-6 libtinfo6 libunistring2 libuuid1 libxml2 libxslt1.1 locales procps tar zlib1g
-RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "postgresql-repmgr" "10.19.0-1" --checksum d4f2261f855e87f4f7fa8f9eaa923798d8824938a5fd8f9eb1ac4782a82f9f09
+RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "postgresql-repmgr" "10.19.0-1" --checksum d4f2261f855e87f4f7fa8f9eaa923798d8824938a5fd8f9eb1ac4782a82f9f00
RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "gosu" "1.14.0-0" --checksum 3e6fc37ca073b10a73a804d39c2f0c028947a1a596382a4f8ebe43dfbaa3a25e
RUN chmod g+rwX /opt/bitnami
RUN localedef -c -f UTF-8 -i en_US en_US.UTF-8
```
```console
$ docker build . -t carrodher/test
Sending build context to Docker daemon  207.4kB
...
Step 6/20 : RUN . /opt/bitnami/scripts/libcomponent.sh && component_unpack "postgresql-repmgr" "10.19.0-1" --checksum d4f2261f855e87f4f7fa8f9eaa923798d8824938a5fd8f9eb1ac4782a82f9f00
 ---> Running in c704d68ca8f6
Downloading postgresql-repmgr-10.19.0-1-linux-amd64-debian-10 package
Verifying package integrity
sha256sum: WARNING: 1 computed checksum did NOT match
postgresql-repmgr-10.19.0-1-linux-amd64-debian-10.tar.gz: FAILED
The command '/bin/sh -c . /opt/bitnami/scripts/libcomponent.sh && component_unpack "postgresql-repmgr" "10.19.0-1" --checksum d4f2261f855e87f4f7fa8f9eaa923798d8824938a5fd8f9eb1ac4782a82f9f00' returned a non-zero code: 1

$ echo $?
1
```

I'm closing the issue since the problem is solved. Thanks again for reporting the issue!

**Closed by carrodher** 2022-01-04 15:42 UTC
Labels: on-hold
