### ISSUE TITLE
repmgr extension not found on this node

### ISSUE THREAD

**Issue by kfirfer** [bitnami/bitnami-docker-postgresql-repmgr#40] opened 2020-10-03 02:32 UTC
Hello

Im getting this errors:
```
postgresql-repmgr 02:27:44.11 INFO  ==> ** Starting repmgrd **
[2020-10-03 02:27:44] [NOTICE] repmgrd (repmgrd 5.1.0) starting up
[2020-10-03 02:27:44] [ERROR] repmgr extension not found on this node
[2020-10-03 02:27:44] [DETAIL] repmgr extension is available but not installed in database "repmgr"
[2020-10-03 02:27:44] [HINT] check that this node is part of a repmgr cluster
```

Tried to deploy postgresql-ha from chart version: 3.8.1

This is my configuration I override the "values.yaml" came with the chart:

```
global:
  postgresql:
    password: "<password>"
    database: "sonarDB"
  pgpool:
    adminPassword: "<password>"

postgresqlImage:
  debug: true

postgresql:
  podAnnotations:
    "backup.velero.io/backup-volumes": "data"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - postgresql
          topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 1
      memory: 1Gi
  livenessProbe:
    enabled: false

pgpool:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - pgpool
          topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  livenessProbe:
    timeoutSeconds: 10

metrics:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 1000m
      memory: 512Mi

persistence:
  size: 5Gi

networkPolicy:
  enabled: true
  allowExternal: false
```

This is the full debug log:

```
vostro@dev101:~/code/kfirfer/helm-charts$ kubectl logs postgresql-ha-postgresql-0 postgresql                         
postgresql-repmgr 02:27:43.57 
postgresql-repmgr 02:27:43.57 Welcome to the Bitnami postgresql-repmgr container
postgresql-repmgr 02:27:43.57 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql-repmgr
postgresql-repmgr 02:27:43.57 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql-repmgr/issues
postgresql-repmgr 02:27:43.57 
postgresql-repmgr 02:27:43.58 DEBUG ==> Configuring libnss_wrapper...
postgresql-repmgr 02:27:43.58 INFO  ==> ** Starting PostgreSQL with Replication Manager setup **
postgresql-repmgr 02:27:43.60 INFO  ==> Validating settings in REPMGR_* env vars...
postgresql-repmgr 02:27:43.60 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql-repmgr 02:27:43.60 INFO  ==> Querying all partner nodes for common upstream node...
postgresql-repmgr 02:27:43.61 DEBUG ==> Checking node 'postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.sonarqube.svc.cluster.local:5432'...
psql: could not connect to server: Connection refused
        Is the server running on host "postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.sonarqube.svc.cluster.local" (172.16.206.253) and accepting
        TCP/IP connections on port 5432?
postgresql-repmgr 02:27:43.61 DEBUG ==> Skipping: failed to get primary from the node 'postgresql-ha-postgresql-0.postgresql-ha-postgresql-headless.sonarqube.svc.cluster.local:5432'!
postgresql-repmgr 02:27:43.61 DEBUG ==> Checking node 'postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.sonarqube.svc.cluster.local:5432'...
psql: could not translate host name "postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.sonarqube.svc.cluster.local" to address: Name or service not known
postgresql-repmgr 02:27:43.62 DEBUG ==> Skipping: failed to get primary from the node 'postgresql-ha-postgresql-1.postgresql-ha-postgresql-headless.sonarqube.svc.cluster.local:5432'!
postgresql-repmgr 02:27:43.62 INFO  ==> There are no nodes with primary role. Assuming the primary role...
postgresql-repmgr 02:27:43.63 INFO  ==> Preparing PostgreSQL configuration...
postgresql-repmgr 02:27:43.63 DEBUG ==> Injecting a new postgresql.conf file...
postgresql-repmgr 02:27:43.63 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql-repmgr 02:27:43.67 DEBUG ==> Injecting a new pg_hba.conf file...
postgresql-repmgr 02:27:43.68 INFO  ==> Preparing repmgr configuration...
postgresql-repmgr 02:27:43.68 DEBUG ==> Node ID: '1000', Rol: 'primary', Primary Node: ':5432'
postgresql-repmgr 02:27:43.68 INFO  ==> Initializing Repmgr...
postgresql-repmgr 02:27:43.68 INFO  ==> Initializing PostgreSQL database...
postgresql-repmgr 02:27:43.69 INFO  ==> Cleaning stale /bitnami/postgresql/data/postmaster.pid file
postgresql-repmgr 02:27:43.70 DEBUG ==> Copying files from /bitnami/postgresql/conf to /opt/bitnami/postgresql/conf
postgresql-repmgr 02:27:43.70 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/postgresql.conf detected
postgresql-repmgr 02:27:43.70 INFO  ==> Custom configuration /opt/bitnami/postgresql/conf/pg_hba.conf detected
postgresql-repmgr 02:27:43.70 DEBUG ==> Ensuring expected directories/files exist...
postgresql-repmgr 02:27:43.71 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql-repmgr 02:27:43.73 INFO  ==> Configuring replication parameters
postgresql-repmgr 02:27:43.75 INFO  ==> Configuring fsync
postgresql-repmgr 02:27:43.75 DEBUG ==> Skipping repmgr configuration...
postgresql-repmgr 02:27:43.75 INFO  ==> Stopping PostgreSQL...
postgresql-repmgr 02:27:43.76 INFO  ==> ** PostgreSQL with Replication Manager setup finished! **

postgresql-repmgr 02:27:43.77 INFO  ==> Starting PostgreSQL in background...
waiting for server to start....2020-10-03 02:27:43.795 GMT [144] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-10-03 02:27:43.795 GMT [144] LOG:  listening on IPv6 address "::", port 5432
2020-10-03 02:27:43.797 GMT [144] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-10-03 02:27:43.805 GMT [144] LOG:  redirecting log output to logging collector process
2020-10-03 02:27:43.805 GMT [144] HINT:  Future log output will appear in directory "/opt/bitnami/postgresql/logs".
2020-10-03 02:27:43.808 GMT [146] LOG:  database system was interrupted; last known up at 2020-10-03 02:27:22 GMT
2020-10-03 02:27:44.018 GMT [146] LOG:  database system was not properly shut down; automatic recovery in progress
2020-10-03 02:27:44.020 GMT [146] LOG:  redo starts at 0/16585A8
2020-10-03 02:27:44.020 GMT [146] LOG:  invalid record length at 0/1658698: wanted 24, got 0
2020-10-03 02:27:44.020 GMT [146] LOG:  redo done at 0/1658650
2020-10-03 02:27:44.020 GMT [146] LOG:  last completed transaction was at log time 2020-10-03 02:27:23.078769+00
2020-10-03 02:27:44.028 GMT [144] LOG:  database system is ready to accept connections
 done
server started
postgresql-repmgr 02:27:44.11 INFO  ==> ** Starting repmgrd **
[2020-10-03 02:27:44] [NOTICE] repmgrd (repmgrd 5.1.0) starting up
[2020-10-03 02:27:44] [ERROR] repmgr extension not found on this node
[2020-10-03 02:27:44] [DETAIL] repmgr extension is available but not installed in database "repmgr"
[2020-10-03 02:27:44] [HINT] check that this node is part of a repmgr cluster
```

**Comment by andresbono** [comment] 2020-10-05 07:20
Hi @kfirfer, thanks for opening this issue. Could it be a duplicate of https://github.com/bitnami/charts/issues/1880?

**Comment by kfirfer** [comment] 2020-10-05 07:24
Hi @andresbono 
Its seems like he having the same problem

**Comment by andresbono** [comment] 2020-10-05 07:29
Then let's close this one in favor of https://github.com/bitnami/charts/issues/1880, good news is they seem to have found the source of the issue and a PR is coming.

**Closed by andresbono** 2020-10-05 07:29 UTC
